# Generated by Django 4.2.18 on 2025-02-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("users", "0005_profile_orcid_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.city",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.country",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_scholar",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.CharField(
                blank=True, default="Independent Researcher", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(blank=True, default="Member", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="related_projects",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="reputation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="No bio available."),
        ),
        migrations.AlterField(
            model_name="profile",
            name="orcid_id",
            field=models.CharField(
                blank=True, default=None, max_length=19, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="users.interest"),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(blank=True, to="users.skill"),
        ),
    ]
