# Generated by Django 4.2.18 on 2025-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_city_profile_country_profile_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="orcid_id",
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
    ]
