# Generated by Django 4.2.18 on 2025-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profile_orcid_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="university_icons/"
                    ),
                ),
            ],
        ),
    ]
