# Generated by Django 4.2.18 on 2025-02-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.university",
            ),
        ),
    ]
